config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
 root 'authors#index'
  get 'authors/index'
  resources :authors, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:new, :create] 
      resources :likes, only: [ :new, :create] 
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(author)
    can :read, Post

    return unless author.present? # additional permissions for logged in users (they can read their own posts)

    can :manage, Post, author: author
    can :manage, Comment, author: author
    can :manage, Like, author: author

    return unless author.role == 'admin' # additional permissions for administrators

    can :manage, :all
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts_per_user
    posts.includes(%i[comments likes]).last(3)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author
  belongs_to :post
  after_save :update_comment_counter

  private

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author
  belongs_to :post
  after_save :update_likes_counter

  # validates :author_id, uniqueness: { scope: :post_id }

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_save :update_posts_counter_per_user
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def five_most_recent_comments_per_post
    comments.includes([:author]).last(5)
  end

  private

  def update_posts_counter_per_user
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_author!

  # to change fro default current_user to current_author
  def current_ability
    @current_ability ||= Ability.new(current_author)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer
      .permit(:sign_up, keys: [:name])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @author = Author.find(params[:author_id])
    @post = Post.find(params[:post_id])
    @comment.author = current_author
    @comment.post = @post

    if @comment.save
      redirect_to author_post_path(@author, @post)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @author = Author.find(params[:author_id])
    @post = Post.find(params[:post_id])
    @like.author = current_author
    @like.post = @post

    if @like.save
      redirect_to author_post_path(@author, @post)
    else
      render :new
      # flash[:notice] = 'Already liked'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @author = Author.find(params[:author_id])
    @author.posts.includes(%i[comments likes])
  end

  def show
    @author = Author.find(params[:author_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_author
    if @post.save
      redirect_to author_path(current_author.id)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to author_path(current_author), notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/_header.html.erb
<header class="header-container">
      <div>
        MyLogo
      </div>
<ul>
  <li><%= link_to 'Home', root_path%></li> 
  <% if author_signed_in?%>  
    <li><%= link_to 'Sign Out', destroy_author_session_path, method: :delete %></li> 
    <li><%= link_to 'Edit Profile', edit_author_registration_path%></li>
    <%= button_to "Logout", destroy_author_session_path, method: :delete, data: { turbo: false }, :class => 'logout' %>
    <% else%> 
    <li><%= link_to 'Sign Up', new_author_registration_path %></li> 
    <li><%= link_to 'Sign In', new_author_session_path%></li> 
    <% end %>
</ul>
  </header>

app/views/authors/index.html.erb
<h1>Authors</h1>
<div class="container">
    <%@authors.includes(:posts).each do |author|  %>
    <%= link_to author_path(author) do %>
    <div class="specific-user">
        <div class="image"> <img  src=<%= author.photo%> > </div>
    <div class="specific-user-content">
        <h2 class="author-name"><%= author.name %></h2>
       <span class="post-counter"> Number of Posts: <%= author.posts.length %></span>
    </div>
    </div>
    <% end %>
    <% end %>
</div>

app/views/authors/show.html.erb
<h1>Authors show</h1>
<div class="container">
    <div class="specific-user">
        <div class="image">
            <img  src=<%= @author.photo%> > 
        </div>
        <div class="specific-user-content">
            <h2><%= @author.name %></h2>
            <span> Number of Posts: <%= @author.posts.length %></span>
        </div>
    </div>

    <div>
        <%= @author.bio%>
    </div>

    <%@author.three_recent_posts_per_user.each do |post|%>
        <div class="posts-container">
            <div class="post-title">
                <%= link_to author_post_path(@author, post) do %>
                    <%= post.title%>
                <% end %>
            </div>
             <p><%= post.text%></p>
             <div class="comments-likes">
                <span> 💬 Comments: <%=post.comments.length%></span>
                <span>Likes: <%= post.likes.length%> </span>
             </div>
             <div class="create_delete_btns">
             <% if can? :destroy, post %>
             <%= button_to "Delete", author_post_path(@author, post), method: :delete, class:"posts-btn" %>
             <% end %>
         </div>
        </div>

    <% end%>
    <div class="buttons">
        <%= link_to author_posts_path(@author) do %>
            <button class="posts-btn">See all Posts </button>
        <% end %>

        <% if current_author.id == @author.id %>
            <%= link_to new_author_post_path(@author) do %>
                <button class="posts-btn">Create new Post </button>
            <% end %>
        <% end %>

    </div>
</div>

app/views/comments/_comment.html.erb
<%= form_with model: Comment, url: author_post_comments_path(@author, @post), class: "comment-form" , id:"comment-form" do |form| %>
        <div>
            
            <%= form.text_field :text, placeholder: "Add a new comment" %>
        </div>
        <div>
            <%= form.submit "Comment:" %>
        </div>
    <% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'authors/header'%>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
 <%= form_with model: Like, url: author_post_likes_path(@author, @post) do |form| %>
        <div>
            <%= form.submit "Like", class:"like"%>
        </div>
    <% end %> 

app/views/posts/index.html.erb
<div class="container">
    <div class="specific-user">
        <div class="image">
            <img  src=<%= @author.photo%> > 
        </div>
        <div class="specific-user-content">
            <h2><%= @author.name %></h2>
            <span>Number of Posts: <%= @author.posts_counter %></span>
        </div>
    </div>

    <%@author.posts.includes([:comments, :likes]).each do |post|%>
        <div class="posts-container">
        
            <div class="post-title">
                <%= link_to author_post_path(@author, post) do %>
                    <%= post.title%>
                <%end%>
            </div>
           
             <p><%= post.text%></p>
             <div class="comments-likes">
             <span>💬 Comments:<%=post.comments.length%></span>
             <span>Likes: <%= post.likes.length%> </span>
             </div>
        </div>
        <div class="post-comment"> 
        <h3 class="comment-title">Comments:</h3>
        <% post.five_most_recent_comments_per_post.each do |comment|%>
            <div> 
                <span> <%= comment.author.name%> </span>: <span><%= comment.text%></span>
            </div>
        
        </div>
       <% end%>  
    <% end%>    
         <button class="pagination-btn">Pagination </button>
</div>

app/views/posts/new.html.erb
<div class="post-form-container">
  <div class="post-form">
    <%= form_with model: Post.new, url:author_posts_path, class:"create-post" do |form| %>

      <%= form.text_field :title, placeholder: "Post title", class:"textarea" %>
      <%= form.text_area :text, size: "70x5", placeholder: "Your post message", class:"textarea"%>
      <%= form.submit "Create", class:"post-btn" %> 

    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div>
<div >
    <h2>Post <%=@post.id%> by: <%= @author.name %></h2>
</div>
    <div class="posts-container-show">
        <h3 class="post-title">
             <%= @post.title%>
        </h3>
        <p><%= @post.text%></p>
        <div class="comments-likes">
        <span> 💬 Comments: <%=@post.comments_counter%></span>
        <span>Likes: <%= @post.likes_counter%> </span>
        </div>
    </div>

    <div class="post-comment"> 
        <h3 class="comment-title">Comments:</h3>
        <%@comments.includes([:author]).each do |comment|%>
            <div> 
                <span> <%= comment.author.name%> </span>: <span><%= comment.text%></span>
            </div> 
        <%end%>
        
        <%= render 'comments/comment'%>
    </div> 
    <div class="comments-likes">
        <%= render 'likes/like'%>
    </div>
</div>
</div>